language: python


python:
  - "3.5"


env:
  global:
    - WEBDAV_URL=http://127.0.0.1/
    - WEBDAV_PUBLIC_URL=http://127.0.0.1/


install:
  - sudo apt-add-repository -y ppa:nginx/development
  - sudo apt-get update
  - sudo apt-get install -y nginx-extras
  - sudo mkdir /webdav
  - sudo chmod -R 0777 /webdav
  - echo "127.0.0.1	webdav-server.com" | sudo tee -a /etc/hosts > /dev/null
  - sudo cp ./webdav.conf /etc/nginx/sites-enabled/webdav.conf
  - sudo service nginx restart
  - pip install -q tox flake8 coverage coveralls


before_script:
  - make flake8


script:
  - tox


after_success:
  - make coveralls
