language: python

python:
  - 3.5
  - 3.6

env:
  global:
    - WEBDAV_URL="http://webdav-server.com/"
    - WEBDAV_PUBLIC_URL="http://webdav-server.com/"

install:
  - bash .travis/install.sh

before_script:
  - flake8 .

script:
  - bash .travis/run.sh
  - tox ${TOXARG}

after_success:
  - coveralls
