language: python


python:
  - "3.5"


env:
  global:
    - WEBDAV_URL="http://webdav-server.com/"
    - WEBDAV_PUBLIC_URL="http://webdav-server.com/"


install:
  - sudo apt-add-repository -y ppa:nginx/development
  - sudo apt-get update
  - sudo apt-get install -y nginx-extras
  - sudo mkdir /webdav
  - sudo chmod -R 0777 /webdav
  - echo "127.0.0.1	webdav-server.com" | sudo tee -a /etc/hosts > /dev/null
  - sudo cp ./nginx.conf  /etc/nginx/nginx.conf
  - sudo cp ./webdav.conf /etc/nginx/webdav.conf
  - sudo service nginx restart
  - pip install -q tox flake8 coverage coveralls


before_script:
  - make flake8


script:
  - WEBDAV_URL="${WEBDAV_URL}" WEBDAV_PUBLIC_URL="${WEBDAB_PUBLIC_URL}" tox


after_success:
  - make coveralls
