language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  global:
    - WEBDAV_URL="http://webdav-server.com/"
    - WEBDAV_PUBLIC_URL="http://webdav-server.com/"
    - WEBDAV_LISTING_BACKEND="django_webdav_storage.listing.nginx_autoindex"

install:
  - bash .travis/install.sh
  - pip install -q tox tox-travis flake8

before_script:
  - flake8 .

script:
  - tox

after_success:
  - coveralls
