language: python

python:
  - "3.4"

env:
  global:
    - WEBDAV_URL=http://127.0.0.1/
    - WEBDAV_PUBLIC_URL=http://127.0.0.1/

  matrix:
    - TOXENV=py27-dj17
    - TOXENV=py27-dj18
    - TOXENV=py27-dj19
    - TOXENV=py34-dj17
    - TOXENV=py34-dj18
    - TOXENV=py34-dj19
    - TOXENV=py35-dj18
    - TOXENV=py35-dj19

install:
  - sudo apt-add-repository -y ppa:nginx/development
  - sudo apt-get update
  - sudo apt-get install -y nginx-extras
  - sudo mkdir /webdav
  - sudo chmod -R 0777 /webdav
  - echo "127.0.0.1	webdav-server.com" |sudo tee -a /etc/hosts > /dev/null
  - sudo cp ./webdav.conf /etc/nginx/sites-enabled/webdav.conf
  - sudo service nginx restart

before_script:
  - make flake8

script:
  - make coverage

after_success:
  - make coveralls
